spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: false
    url: ${JDBC_URL}
    user: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}
logging:
  level:
    org.springframework.r2dbc.core: debug

riot:
  api:
    url: ${RIOT_API_URL}
    key: ${RIOT_API_KEY}

springdoc:
  swagger-ui:
    path: /swagger-ui/swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /swagger-ui/api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json