spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  flyway:
    enabled: true
    url: ${JDBC_URL}
    user: ${JDBC_USERNAME}
    password: ${JDBC_PASSWORD}

logging:
  level:
    org.springframework.r2dbc.core: debug

riot:
  api:
    url : ${RIOT_API_URL}
    key : ${RIOT_API_KEY}